// Complete Blood on the Clocktower character data
export interface Character {
  id: string;
  name: string;
  edition: 'tb' | 'snv' | 'bmr' | 'experimental' | 'traveler';
  team: 'townsfolk' | 'outsider' | 'minion' | 'demon' | 'traveler';
  ability: string;
  firstNightOrder: number | null;  // null = doesn't wake
  otherNightOrder: number | null;
  setup: boolean;  // affects game setup (Baron, Godfather, etc.)
  reminders: string[];
  // Extended info
  flavorQuote: string;
  extendedSummary: string;  // Detailed rules explanation
  tipsAndTricks: string[];  // Array of tips for playing this role
  bluffingAs?: string[];    // For good characters - tips for evil players bluffing as this role
  fightingThe?: string[];   // For evil characters - tips for good players fighting this role
}

export interface Jinx {
  character1: string;
  character2: string;
  reason: string;
}

// ===================
// TROUBLE BREWING
// ===================

export const TROUBLE_BREWING: Character[] = [
  // TOWNSFOLK
  { id: 'washerwoman', name: 'Washerwoman', edition: 'tb', team: 'townsfolk', ability: 'You start knowing that 1 of 2 players is a particular Townsfolk.', firstNightOrder: 32, otherNightOrder: null, setup: false, reminders: ['Townsfolk', 'Wrong'], flavorQuote: '"Bloodstains on a dinner jacket? No, this is cooking sherry. How careless."', extendedSummary: 'On the first night, you learn that one of two players is a specific Townsfolk character. One player is that character, the other is not (they could be any character). This information is true unless you are drunk or poisoned.', tipsAndTricks: ['Share your information early to help the good team', 'Consider who nominated who to verify your info', 'Your info is most useful on day 1'], bluffingAs: ['Claim to have seen two suspicious players', 'Use real player names but fake the character', 'Coordinate with evil team on who to frame'] },
  { id: 'librarian', name: 'Librarian', edition: 'tb', team: 'townsfolk', ability: 'You start knowing that 1 of 2 players is a particular Outsider. (Or that zero are in play.)', firstNightOrder: 33, otherNightOrder: null, setup: false, reminders: ['Outsider', 'Wrong'], flavorQuote: '"Shhhh! This is a library, not a chatroom."', extendedSummary: 'On the first night, you learn that one of two players is a specific Outsider character, or you learn that zero Outsiders are in play. If there are no Outsiders, you learn this definitively.', tipsAndTricks: ['Zero Outsiders info is very powerful - share it', 'Help identify the Drunk if you see one', 'Outsider info helps narrow down evil players'], bluffingAs: ['Claim zero Outsiders to discredit real Outsider claims', 'Point at confirmed good player as Outsider to sow doubt'] },
  { id: 'investigator', name: 'Investigator', edition: 'tb', team: 'townsfolk', ability: 'You start knowing that 1 of 2 players is a particular Minion.', firstNightOrder: 34, otherNightOrder: null, setup: false, reminders: ['Minion', 'Wrong'], flavorQuote: '"It was Professor Plum, in the conservatory, with the lead pipe."', extendedSummary: 'On the first night, you learn that one of two players is a specific Minion character. One is the Minion, one is not. Use this to narrow down the evil team.', tipsAndTricks: ['Your info directly identifies an evil player', 'Work with other info roles to triangulate', 'Execute one of your two players if stuck'], bluffingAs: ['Frame a good player as the Minion', 'Claim a Minion not in play to confuse'] },
  { id: 'chef', name: 'Chef', edition: 'tb', team: 'townsfolk', ability: 'You start knowing how many pairs of evil players there are.', firstNightOrder: 35, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"I\'ve got a very delicate palate. I can tell when something is off."', extendedSummary: 'You learn how many pairs of evil players are sitting next to each other. A pair is two evil players adjacent in the seating. If Demon sits next to Minion, that is 1 pair.', tipsAndTricks: ['Zero means evil players are spread out', 'High numbers mean evil is clustered', 'Combine with other info to find the cluster'], bluffingAs: ['Claim a number that matches the actual seating', 'Zero is safest if you do not know evil positions'] },
  { id: 'empath', name: 'Empath', edition: 'tb', team: 'townsfolk', ability: 'Each night, you learn how many of your 2 alive neighbours are evil.', firstNightOrder: 36, otherNightOrder: 53, setup: false, reminders: [], flavorQuote: '"I feel your pain. All of it."', extendedSummary: 'Each night, you learn how many of your two alive neighbors are evil (0, 1, or 2). Dead players are skipped - your neighbors are the closest alive players on each side.', tipsAndTricks: ['Track your number each night as players die', 'Consistent zeros mean your neighbors are good', 'Changing numbers help identify who died'], bluffingAs: ['Claim numbers that match dead/alive status', 'Harder to fake as game progresses'] },
  { id: 'fortuneteller', name: 'Fortune Teller', edition: 'tb', team: 'townsfolk', ability: 'Each night, choose 2 players: you learn if either is a Demon. There is a good player that registers as a Demon to you.', firstNightOrder: 37, otherNightOrder: 54, setup: false, reminders: ['Red Herring'], flavorQuote: '"I see a strangled man with blood on his chin."', extendedSummary: 'Each night, pick two players. You learn Yes if either is the Demon. But there is one good player (Red Herring) who always registers as Demon to you, creating false positives.', tipsAndTricks: ['Use process of elimination to find the Red Herring', 'A Yes could be Demon OR Red Herring', 'Multiple Yeses on same player is suspicious'], bluffingAs: ['Claim Yes on players you want executed', 'Red Herring excuse covers mistakes'] },
  { id: 'undertaker', name: 'Undertaker', edition: 'tb', team: 'townsfolk', ability: 'Each night*, you learn which character died by execution today.', firstNightOrder: null, otherNightOrder: 55, setup: false, reminders: ['Executed'], flavorQuote: '"Toe-tags and cold slabs. That\'s the life."', extendedSummary: 'Each night after the first, you learn the character of the player who was executed during the day. If no one was executed, you learn nothing.', tipsAndTricks: ['Verify claimed roles of executed players', 'Helps identify liars retrospectively', 'Drunk/poisoned players show their real role'], bluffingAs: ['Confirm executed evil players as good', 'Hard to fake consistently'] },
  { id: 'monk', name: 'Monk', edition: 'tb', team: 'townsfolk', ability: 'Each night*, choose a player (not yourself): they are safe from the Demon tonight.', firstNightOrder: null, otherNightOrder: 12, setup: false, reminders: ['Protected'], flavorQuote: '"\'Twas a prayer of St Benedict that kept the beast at bay."', extendedSummary: 'Each night except the first, choose a player other than yourself. They cannot be killed by the Demon tonight. You cannot protect yourself.', tipsAndTricks: ['Protect players who seem most valuable', 'Vary your protection to avoid patterns', 'Coming out risks Demon avoiding your target'], bluffingAs: ['Claim to have protected dead players', 'Explain why Demon did not kill someone'] },
  { id: 'ravenkeeper', name: 'Ravenkeeper', edition: 'tb', team: 'townsfolk', ability: 'If you die at night, you are woken to choose a player: you learn their character.', firstNightOrder: null, otherNightOrder: 52, setup: false, reminders: [], flavorQuote: '"My birds will find the truth, no matter where it hides."', extendedSummary: 'If you die at night (killed by Demon or other means), you wake immediately and choose any player. You learn their exact character. Does not trigger on execution.', tipsAndTricks: ['Check suspicious players or confirm allies', 'Your info is very reliable if you die', 'Consider who benefits from your death'], bluffingAs: ['Claim to have died and learned info', 'Requires being "dead" to activate'] },
  { id: 'virgin', name: 'Virgin', edition: 'tb', team: 'townsfolk', ability: 'The 1st time you are nominated, if the nominator is a Townsfolk, they are executed immediately.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: ['No Ability'], flavorQuote: '"I am pure. I have never sinned."', extendedSummary: 'The first time you are nominated, if the nominating player is a Townsfolk, they die immediately. If they are not Townsfolk (Outsider, Minion, Demon), nothing happens and you lose your ability.', tipsAndTricks: ['Ask trusted Townsfolk NOT to nominate you', 'Evil players nominating you proves they are evil', 'Use your ability to test suspicious players'], bluffingAs: ['Dangerous bluff - real Virgin kills Townsfolk nominators', 'Only bluff if you can avoid nomination'] },
  { id: 'slayer', name: 'Slayer', edition: 'tb', team: 'townsfolk', ability: 'Once per game, during the day, publicly choose a player: if they are the Demon, they die.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: ['No Ability'], flavorQuote: '"Die, foul beast!"', extendedSummary: 'Once per game, during the day, publicly declare that you are the Slayer and choose a player. If that player is the Demon, they die immediately and good wins. Otherwise, nothing visible happens.', tipsAndTricks: ['Save your shot for when you are confident', 'A miss does not prove innocence (you could be drunk)', 'Coordinate with info roles before using'], bluffingAs: ['Claim you used it and missed', 'Use to "clear" an evil player'] },
  { id: 'soldier', name: 'Soldier', edition: 'tb', team: 'townsfolk', ability: 'You are safe from the Demon.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"As long as I have my faith, I am invincible."', extendedSummary: 'The Demon cannot kill you. If the Demon chooses you, you do not die and the Demon does not learn why. You can still die from other causes like execution.', tipsAndTricks: ['Coming out as Soldier is risky - evil may execute you', 'Surviving a night proves nothing (Monk, Soldier, etc)', 'Stay quiet and observe who pushes for your execution'], bluffingAs: ['Explain why you survived the night', 'Safer bluff for evil players'] },
  { id: 'mayor', name: 'Mayor', edition: 'tb', team: 'townsfolk', ability: 'If only 3 players live & no execution occurs, your team wins. If you die at night, another player might die instead.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Let me be frank with you..."', extendedSummary: 'If exactly 3 players are alive and no execution occurs that day, good wins. Also, if the Demon tries to kill you at night, another player might die instead (Storyteller decides).', tipsAndTricks: ['Push for no execution at 3 players', 'Your redirect ability is unreliable', 'Coming out late can enable win condition'], bluffingAs: ['Risky - evil cannot win with real Mayor at 3', 'Claim if pushing for executions at 3 players'] },
  
  // OUTSIDERS
  { id: 'butler', name: 'Butler', edition: 'tb', team: 'outsider', ability: 'Each night, choose a player (not yourself): tomorrow, you may only vote if they are voting too.', firstNightOrder: 38, otherNightOrder: 56, setup: false, reminders: ['Master'], flavorQuote: '"Yes, sir."', extendedSummary: 'Each night, you choose a Master. The next day, you may only have your hand raised to vote if your Master also has their hand raised. You can nominate freely.', tipsAndTricks: ['Choose players you trust as Master', 'Evil Master can control your vote', 'Tell good players you are Butler so they understand'], bluffingAs: ['Explain restricted voting behavior', 'Good cover for not voting on certain executions'] },
  { id: 'drunk', name: 'Drunk', edition: 'tb', team: 'outsider', ability: 'You do not know you are the Drunk. You think you are a Townsfolk character, but you are not.', firstNightOrder: null, otherNightOrder: null, setup: true, reminders: [], flavorQuote: '"I\'m not as think as you drunk I am."', extendedSummary: 'You do not know you are the Drunk. The Storyteller tells you that you are a Townsfolk and gives you false information matching that ability. You register as Drunk, not as that Townsfolk.', tipsAndTricks: ['If your info makes no sense, you might be Drunk', 'Drunk is in play - someone is getting false info', 'Compare info with others to find inconsistencies'], bluffingAs: ['Cannot directly bluff as Drunk (you would not know)', 'Claim Townsfolk and explain bad info as Drunk'] },
  { id: 'recluse', name: 'Recluse', edition: 'tb', team: 'outsider', ability: 'You might register as evil & as a Minion or Demon, even if dead.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Do not come near me. I am unclean."', extendedSummary: 'You might register as evil to abilities that detect alignment. You might register as a Minion or Demon to abilities that detect character type. The Storyteller decides each time.', tipsAndTricks: ['Warn info roles you exist', 'You can make good info look wrong', 'Coming out early helps the team adjust'], bluffingAs: ['Great cover for evil - claim you are the Recluse', 'Explains why you appear evil to abilities'] },
  { id: 'saint', name: 'Saint', edition: 'tb', team: 'outsider', ability: 'If you die by execution, your team loses.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Forgive them, for they know not what they do."', extendedSummary: 'If you are executed and die, good loses immediately. Even if you are the Imp and die by execution, good loses. Be very careful about nomination patterns.', tipsAndTricks: ['Come out early so town does not execute you', 'Evil will try to frame you as Demon', 'Stay alive at all costs through voting'], bluffingAs: ['Risky - real Saint loses if executed', 'Claim Saint to avoid execution pressure'] },

  // MINIONS
  { id: 'poisoner', name: 'Poisoner', edition: 'tb', team: 'minion', ability: 'Each night, choose a player: they are poisoned tonight and tomorrow day.', firstNightOrder: 17, otherNightOrder: 7, setup: false, reminders: ['Poisoned'], flavorQuote: '"A little something for the pain..."', extendedSummary: 'Each night, choose a player. They are poisoned until dusk tomorrow. While poisoned, their ability malfunctions - they get false info or their ability does not work.', tipsAndTricks: ['Poison information roles for maximum chaos', 'Coordinate with Demon on who to poison', 'Poisoning Monk lets Demon kill protected players'], fightingThe: ['Look for inconsistent info patterns', 'Multiple people with wrong info suggests Poisoner', 'Consider who benefits from certain info being wrong'] },
  { id: 'spy', name: 'Spy', edition: 'tb', team: 'minion', ability: 'Each night, you see the Grimoire. You might register as good & as a Townsfolk or Outsider, even if dead.', firstNightOrder: 49, otherNightOrder: 68, setup: false, reminders: [], flavorQuote: '"Shhhh."', extendedSummary: 'Each night, you see the Storyteller Grimoire showing all characters and their positions. You might register as good to abilities, letting you fake Townsfolk results.', tipsAndTricks: ['Use Grimoire knowledge to coordinate evil team', 'Your registration lets you appear in good info', 'Know exactly what info roles will learn'], fightingThe: ['Spy can appear as good in info - double check', 'Spy knows everything, so bluffs will be good', 'Look for someone with too much knowledge'] },
  { id: 'scarletwoman', name: 'Scarlet Woman', edition: 'tb', team: 'minion', ability: 'If there are 5 or more players alive & the Demon dies, you become the Demon. (Conditions vary.)', firstNightOrder: null, otherNightOrder: 19, setup: false, reminders: ['Demon'], flavorQuote: '"You thought you won? How delightful."', extendedSummary: 'If the Demon dies while 5+ players are alive, you become the Imp immediately. The game continues with you as the new Demon. Below 5 players, Demon death ends the game.', tipsAndTricks: ['Stay alive as backup Demon', 'Demon can suicide into you to clear suspicion', 'Let Demon take risks knowing you are backup'], fightingThe: ['At 5+ players, killing Demon might not win', 'Execute suspected Scarlet Woman before Demon', 'Watch for player who benefits from Demon death'] },
  { id: 'baron', name: 'Baron', edition: 'tb', team: 'minion', ability: 'There are extra Outsiders in play. [+2 Outsiders]', firstNightOrder: null, otherNightOrder: null, setup: true, reminders: [], flavorQuote: '"I have many friends."', extendedSummary: 'During setup, 2 extra Outsiders are added to the game. This means 2 fewer Townsfolk. The Baron has no other ability during the game.', tipsAndTricks: ['Extra Outsiders create confusion', 'Librarian will see more Outsiders than expected', 'Your presence changes the setup math'], fightingThe: ['Count Outsider claims - Baron adds 2', 'Too many Outsiders means some are lying', 'No Outsider claims might mean no Baron'] },

  // DEMONS
  { id: 'imp', name: 'Imp', edition: 'tb', team: 'demon', ability: 'Each night*, choose a player: they die. If you kill yourself this way, a Minion becomes the Imp.', firstNightOrder: null, otherNightOrder: 24, setup: false, reminders: ['Dead'], flavorQuote: '"We must528 eat. We must feed. Tonight, you."', extendedSummary: 'Each night except the first, choose a player to kill. If you choose yourself, you die and a Minion becomes the new Imp. This "starpass" lets you clear suspicion.', tipsAndTricks: ['Starpass to Minion if you are about to be executed', 'Coordinate with Minions on who becomes next Imp', 'Killing yourself creates alibi for that Minion'], fightingThe: ['Imp can pass to Minion - track all evil, not just Demon', 'Sudden Demon death at night means starpass', 'Execute Minions before they can receive starpass'] },
];

// ===================
// BAD MOON RISING
// ===================

export const BAD_MOON_RISING: Character[] = [
  // TOWNSFOLK
  { id: 'grandmother', name: 'Grandmother', edition: 'bmr', team: 'townsfolk', ability: 'You start knowing a good player & their character. If the Demon kills them, you die too.', firstNightOrder: 39, otherNightOrder: null, setup: false, reminders: ['Grandchild'], flavorQuote: '"Come closer, dearie."', extendedSummary: 'On the first night, you learn a good player and their character (your Grandchild). If the Demon kills your Grandchild, you also die that night.', tipsAndTricks: ['Confirm your Grandchild identity early', 'Protect your Grandchild from Demon', 'Your death might indicate Demon kill pattern'], bluffingAs: ['Claim a player as Grandchild to build trust', 'Risky if your "Grandchild" dies and you live'] },
  { id: 'sailor', name: 'Sailor', edition: 'bmr', team: 'townsfolk', ability: 'Each night, choose an alive player: either you or they are drunk until dusk. You can\'t die.', firstNightOrder: 10, otherNightOrder: 4, setup: false, reminders: ['Drunk'], flavorQuote: '"Shiver me timbers!"', extendedSummary: 'Each night, choose a player. Either you or they become drunk until dusk (Storyteller chooses). You cannot die by any means while sober.', tipsAndTricks: ['You are immortal when sober', 'Choose evil players to potentially drunk them', 'Your survival is guaranteed - use it boldly'], bluffingAs: ['Explain why you survived nights', 'Claim to have made specific players drunk'] },
  { id: 'chambermaid', name: 'Chambermaid', edition: 'bmr', team: 'townsfolk', ability: 'Each night, choose 2 alive players (not yourself): you learn how many woke tonight due to their ability.', firstNightOrder: 50, otherNightOrder: 69, setup: false, reminders: [], flavorQuote: '"I see all that happens in these halls."', extendedSummary: 'Each night, choose 2 players. You learn how many of them woke tonight due to their own ability (0, 1, or 2). Does not count being woken by other abilities.', tipsAndTricks: ['Confirm night-active roles like Monk', 'Zero might mean players are lying about roles', 'Track patterns across multiple nights'], bluffingAs: ['Claim numbers that confirm evil players', 'Complex to fake consistently'] },
  { id: 'exorcist', name: 'Exorcist', edition: 'bmr', team: 'townsfolk', ability: 'Each night*, choose a player (different to last night): the Demon, if chosen, learns who you are then doesn\'t wake tonight.', firstNightOrder: null, otherNightOrder: 21, setup: false, reminders: ['Chosen'], flavorQuote: '"The power of good compels you!"', extendedSummary: 'Each night except the first, choose a player (different from last night). If you choose the Demon, they learn you are the Exorcist and cannot kill tonight.', tipsAndTricks: ['No death means you hit the Demon', 'Demon knows who you are after you hit them', 'Rotate choices to eventually find Demon'], bluffingAs: ['Claim you caused a death-free night', 'Demon can confirm or deny your claims'] },
  { id: 'innkeeper', name: 'Innkeeper', edition: 'bmr', team: 'townsfolk', ability: 'Each night*, choose 2 players: they can\'t die tonight, but 1 is drunk until dusk.', firstNightOrder: null, otherNightOrder: 9, setup: false, reminders: ['Protected', 'Drunk'], flavorQuote: '"Come in, come in! The fire is warm."', extendedSummary: 'Each night except the first, choose 2 players. They cannot die tonight. However, one of them becomes drunk until dusk (Storyteller chooses which).', tipsAndTricks: ['Protect key players from Demon', 'One of your choices gets false info', 'Balance protection with drunking drawback'], bluffingAs: ['Explain why certain players survived', 'Claim responsibility for info discrepancies'] },
  { id: 'gambler', name: 'Gambler', edition: 'bmr', team: 'townsfolk', ability: 'Each night*, choose a player & guess their character: if you guess wrong, you die.', firstNightOrder: null, otherNightOrder: 3, setup: false, reminders: ['Dead'], flavorQuote: '"All in."', extendedSummary: 'Each night except the first, choose a player and guess their character. If you guess correctly, nothing happens. If you guess wrong, you die.', tipsAndTricks: ['Guess confirmed players to stay safe', 'Correct guess confirms identity', 'High risk ability - use carefully'], bluffingAs: ['Claim correct guesses on specific players', 'Death explains why you stop claiming'] },
  { id: 'gossip', name: 'Gossip', edition: 'bmr', team: 'townsfolk', ability: 'Each day, you may make a public statement. Tonight, if it was true, a player dies.', firstNightOrder: null, otherNightOrder: 37, setup: false, reminders: ['Dead'], flavorQuote: '"Did you hear? Did you hear?"', extendedSummary: 'Each day, you may make a public statement. That night, if your statement was true, a player dies (Storyteller chooses who). False statements cause no death.', tipsAndTricks: ['Make obviously false statements to avoid kills', 'True statements kill - be careful with facts', 'Use as information by tracking which statements killed'], bluffingAs: ['Claim Gossip to explain random deaths', 'Complex ability to fake'] },
  { id: 'courtier', name: 'Courtier', edition: 'bmr', team: 'townsfolk', ability: 'Once per game, at night, choose a character: they are drunk for 3 nights & 3 days.', firstNightOrder: 18, otherNightOrder: 8, setup: false, reminders: ['Drunk 1', 'Drunk 2', 'Drunk 3', 'No Ability'], flavorQuote: '"I know exactly what to say."', extendedSummary: 'Once per game, choose a character (not a player). That character becomes drunk for 3 days and 3 nights. Works on any character in play.', tipsAndTricks: ['Drunk the Demon to prevent kills', 'Target evil characters for maximum impact', 'Save for when you identify a threat'], bluffingAs: ['Claim to have drunked specific characters', 'Explain why certain abilities malfunctioned'] },
  { id: 'professor', name: 'Professor', edition: 'bmr', team: 'townsfolk', ability: 'Once per game, at night*, choose a dead player: if they are a Townsfolk, they are resurrected.', firstNightOrder: null, otherNightOrder: 43, setup: false, reminders: ['Alive', 'No Ability'], flavorQuote: '"I have studied the dark arts, but only for good."', extendedSummary: 'Once per game, at night (not the first), choose a dead player. If they were a Townsfolk, they come back to life. If not Townsfolk, nothing happens.', tipsAndTricks: ['Resurrect confirmed Townsfolk', 'Failed resurrection reveals non-Townsfolk', 'Powerful ability - choose wisely'], bluffingAs: ['Claim failed resurrection on Outsider/evil', 'Hard to fake successful resurrection'] },
  { id: 'minstrel', name: 'Minstrel', edition: 'bmr', team: 'townsfolk', ability: 'When a Minion dies by execution, all other players (except Travellers) are drunk until dusk tomorrow.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: ['Everyone Drunk'], flavorQuote: '"A song for the fallen..."', extendedSummary: 'When a Minion is executed, all players except Travellers become drunk until dusk the next day. Minstrel is also drunk. This is passive.', tipsAndTricks: ['Executing Minion causes mass drunkenness', 'Demon attacks still happen while drunk', 'Plan around potential drunk day'], bluffingAs: ['Claim Minstrel to explain mass confusion', 'Passive ability is easy to claim'] },
  { id: 'tealady', name: 'Tea Lady', edition: 'bmr', team: 'townsfolk', ability: 'If both your alive neighbours are good, they can\'t die.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: ['Protected'], flavorQuote: '"Would you like a cup of tea?"', extendedSummary: 'If both your alive neighbours are good, they cannot die by any means. If one neighbour is evil, this protection is lost.', tipsAndTricks: ['Sit between trusted good players', 'Your neighbours being alive is strong', 'Evil will try to break your chain'], bluffingAs: ['Explain why neighbours survived', 'Requires knowledge of neighbour alignments'] },
  { id: 'pacifist', name: 'Pacifist', edition: 'bmr', team: 'townsfolk', ability: 'Executed good players might not die.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Violence is never the answer."', extendedSummary: 'When a good player is executed, they might not die. The Storyteller decides. This is passive and always active while you are alive and sober.', tipsAndTricks: ['Good players might survive execution', 'Creates uncertainty around executions', 'Evil will want you dead'], bluffingAs: ['Explain why executed players survived', 'Passive - easy to claim'] },
  { id: 'fool', name: 'Fool', edition: 'bmr', team: 'townsfolk', ability: 'The first time you die, you don\'t.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: ['No Ability'], flavorQuote: '"La la la!"', extendedSummary: 'The first time you would die (by any cause), you do not die. You appear to die but survive. After this, you die normally.', tipsAndTricks: ['You get one free death', 'Coming out can waste Demon attacks', 'Execution survival is very suspicious'], bluffingAs: ['Explain surviving night attack', 'Only works for first death'] },

  // OUTSIDERS
  { id: 'tinker', name: 'Tinker', edition: 'bmr', team: 'outsider', ability: 'You might die at any time.', firstNightOrder: null, otherNightOrder: 48, setup: false, reminders: ['Dead'], flavorQuote: '"I wonder what this button does..."', extendedSummary: 'The Storyteller may kill you at any time - day or night, for any reason or no reason. Your death can happen suddenly without warning.', tipsAndTricks: ['Your random death confuses investigations', 'Come out so team knows deaths may be random', 'Storyteller usually kills you at dramatic moments'], bluffingAs: ['Cannot reliably bluff Tinker', 'Your death pattern must be unpredictable'] },
  { id: 'moonchild', name: 'Moonchild', edition: 'bmr', team: 'outsider', ability: 'When you learn that you died, publicly choose 1 alive player. Tonight, if it was a good player, they die.', firstNightOrder: null, otherNightOrder: 49, setup: false, reminders: ['Dead'], flavorQuote: '"The moon speaks to me."', extendedSummary: 'When you die (and learn it), immediately choose a living player publicly. That night, if your choice was a good player, they die.', tipsAndTricks: ['Choose someone you think is evil', 'Wrong guess kills a good player', 'Death trigger is immediate and public'], bluffingAs: ['Risky - wrong choice kills good player', 'Creates pressure on your target'] },
  { id: 'goon', name: 'Goon', edition: 'bmr', team: 'outsider', ability: 'Each night, the 1st player to choose you with their ability is drunk until dusk. You become their alignment.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: ['Drunk'], flavorQuote: '"I do what I\'m told."', extendedSummary: 'Each night, the first player to target you with an ability becomes drunk until dusk. You become their alignment (good or evil).', tipsAndTricks: ['Your alignment can flip to evil', 'Drunking abilities that target you', 'Complex interactions - track carefully'], bluffingAs: ['Explain alignment confusion', 'Complex ability to fake'] },
  { id: 'lunatic', name: 'Lunatic', edition: 'bmr', team: 'outsider', ability: 'You think you are a Demon, but you are not. The Demon knows who you are & who you choose at night.', firstNightOrder: 7, otherNightOrder: 22, setup: true, reminders: ['Attack 1', 'Attack 2', 'Attack 3'], flavorQuote: '"I am the night!"', extendedSummary: 'You are told you are the Demon and "kill" each night, but you are actually the Lunatic. The real Demon knows who you are and sees your choices.', tipsAndTricks: ['Your kills do not happen', 'Real Demon uses your choices as info', 'When you realize, help good team'], bluffingAs: ['Cannot bluff Lunatic - you would not know', 'Demon can claim to be Lunatic'] },

  // MINIONS
  { id: 'godfather', name: 'Godfather', edition: 'bmr', team: 'minion', ability: 'You start knowing which Outsiders are in play. If 1 died today, choose a player tonight: they die. [-1 or +1 Outsider]', firstNightOrder: 20, otherNightOrder: 38, setup: true, reminders: ['Dead', 'Died Today'], flavorQuote: '"I\'ll make you an offer you can\'t refuse."', extendedSummary: 'You start knowing which Outsiders are in play. On nights after an Outsider dies that day, you choose a player to kill. Setup modifies Outsider count by 1.', tipsAndTricks: ['Kill on nights after Outsider deaths', 'Use Outsider knowledge strategically', 'Second kill makes for deadly nights'], fightingThe: ['Track Outsider deaths and night kills', 'Second kill on some nights suggests Godfather', 'Outsider count may be modified'] },
  { id: 'devilsadvocate', name: 'Devil\'s Advocate', edition: 'bmr', team: 'minion', ability: 'Each night, choose a living player (different to last night): if executed tomorrow, they don\'t die.', firstNightOrder: 21, otherNightOrder: 13, setup: false, reminders: ['Survives'], flavorQuote: '"I am simply presenting the other side."', extendedSummary: 'Each night, choose a player (different from last night). If that player is executed tomorrow, they survive the execution.', tipsAndTricks: ['Protect Demon from execution', 'Protect yourself if suspected', 'Failed executions create confusion'], fightingThe: ['Execute same player twice', 'Surviving execution is suspicious', 'DA must switch targets each night'] },
  { id: 'assassin', name: 'Assassin', edition: 'bmr', team: 'minion', ability: 'Once per game, at night*, choose a player: they die, even if for some reason they could not.', firstNightOrder: null, otherNightOrder: 36, setup: false, reminders: ['Dead', 'No Ability'], flavorQuote: '"Silent. Deadly. Professional."', extendedSummary: 'Once per game, at night (not the first), choose a player. They die, bypassing all protection. Kills through Sailor, Tea Lady, etc.', tipsAndTricks: ['Save for protected targets', 'Bypass all death prevention', 'Coordinate with Demon timing'], fightingThe: ['One unstoppable kill from Assassin', 'Protected player dying suggests Assassin', 'Only works once per game'] },
  { id: 'mastermind', name: 'Mastermind', edition: 'bmr', team: 'minion', ability: 'If the Demon dies by execution (ending the game), play for 1 more day. If a player is then executed, their team loses.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"All according to plan."', extendedSummary: 'If the Demon dies by execution (which would end the game), play continues for one more day. Whoever is executed on that day - their team loses.', tipsAndTricks: ['Insurance against Demon execution', 'Extra day creates pressure', 'Evil can win even after Demon dies'], fightingThe: ['Mastermind gives evil extra day', 'Be careful who you execute after Demon', 'No execution on Mastermind day wins for good'] },

  // DEMONS
  { id: 'zombuul', name: 'Zombuul', edition: 'bmr', team: 'demon', ability: 'Each night*, if no-one died today, choose a player: they die. The 1st time you die, you live but register as dead.', firstNightOrder: null, otherNightOrder: 25, setup: false, reminders: ['Dead', 'Died Today'], flavorQuote: '"Braaaaains..."', extendedSummary: 'You only kill at night if no one died during the day. First time you die, you appear dead but continue playing secretly.', tipsAndTricks: ['Execute daily to limit Zombuul kills', 'First death is fake - Zombuul continues', 'No daytime death means night kill'], fightingThe: ['Execute someone every day', 'Zombuul appears dead but is not', 'Watch for continued evil activity after death'] },
  { id: 'pukka', name: 'Pukka', edition: 'bmr', team: 'demon', ability: 'Each night, choose a player: they are poisoned. The previously poisoned player dies then becomes healthy.', firstNightOrder: 27, otherNightOrder: 26, setup: false, reminders: ['Poisoned', 'Dead'], flavorQuote: '"Ssssleep now..."', extendedSummary: 'Each night (including first), choose a player to poison. The previously poisoned player dies and becomes healthy. Creates delayed deaths.', tipsAndTricks: ['Poison tonight, they die tomorrow night', 'Delayed death creates alibi confusion', 'First night poison, no death yet'], fightingThe: ['Deaths are delayed by one night', 'Player was poisoned before they died', 'Info from dying player may be false'] },
  { id: 'shabaloth', name: 'Shabaloth', edition: 'bmr', team: 'demon', ability: 'Each night*, choose 2 players: they die. A dead player you chose last night might be regurgitated.', firstNightOrder: null, otherNightOrder: 27, setup: false, reminders: ['Dead', 'Alive'], flavorQuote: '"Nom nom nom."', extendedSummary: 'Each night except the first, choose 2 players to kill. One player you killed the previous night might come back to life.', tipsAndTricks: ['Double kills accelerate game', 'Regurgitation brings back victim', 'High body count Demon'], fightingThe: ['Two deaths per night is Shabaloth', 'Resurrection possible from Shabaloth', 'Fast-paced game requires quick action'] },
  { id: 'po', name: 'Po', edition: 'bmr', team: 'demon', ability: 'Each night*, you may choose a player: they die. If your last choice was no-one, choose 3 players tonight.', firstNightOrder: null, otherNightOrder: 28, setup: false, reminders: ['Dead', 'Dead', 'Dead', '3 Attacks'], flavorQuote: '"Charge!"', extendedSummary: 'Each night except first, you may choose a player to kill (or no one). If you chose no one last night, you must kill 3 players tonight.', tipsAndTricks: ['Skip a night to enable triple kill', 'Triple kill is devastating', 'Pacing kills strategically'], fightingThe: ['No death might mean Po charging', 'Triple kill follows no-kill night', 'High variance in death count'] },
];

// ===================
// SECTS & VIOLETS
// ===================

export const SECTS_AND_VIOLETS: Character[] = [
  // TOWNSFOLK
  { id: 'clockmaker', name: 'Clockmaker', edition: 'snv', team: 'townsfolk', ability: 'You start knowing how many steps from the Demon to its nearest Minion.', firstNightOrder: 40, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Tick, tock, tick, tock."', extendedSummary: 'On night one, you learn the distance (in seats) from the Demon to their nearest Minion, going either direction around the circle.', tipsAndTricks: ['Low number means Demon and Minion sit close', 'Use seating chart to narrow possibilities', 'Combine with other info for triangulation'], bluffingAs: ['Claim numbers that fit evil positions', 'High numbers spread suspicion widely'] },
  { id: 'dreamer', name: 'Dreamer', edition: 'snv', team: 'townsfolk', ability: 'Each night, choose a player (not yourself or Travellers): you learn 1 good and 1 evil character, 1 of which is correct.', firstNightOrder: 41, otherNightOrder: 57, setup: false, reminders: [], flavorQuote: '"I saw it in a dream..."', extendedSummary: 'Each night, choose a player. You learn a good character and an evil character - one is their actual character, one is false.', tipsAndTricks: ['Process of elimination over multiple nights', 'Track which characters keep appearing', 'Coordinate with others for cross-reference'], bluffingAs: ['Create plausible pairs', 'Include real characters in your pairs'] },
  { id: 'snakecharmer', name: 'Snake Charmer', edition: 'snv', team: 'townsfolk', ability: 'Each night, choose an alive player: a chosen Demon swaps characters & alignments with you & is then poisoned.', firstNightOrder: 19, otherNightOrder: 10, setup: false, reminders: ['Poisoned'], flavorQuote: '"Come to me, little one."', extendedSummary: 'Each night, choose a player. If they are the Demon, you swap characters and alignments with them - they become good Snake Charmer, you become evil Demon (but poisoned).', tipsAndTricks: ['Hit the Demon and you become the Demon', 'Now-good Demon was evil, might act evil', 'Your new Demon status is poisoned initially'], bluffingAs: ['Risky ability to claim', 'Hitting Demon changes everything'] },
  { id: 'mathematician', name: 'Mathematician', edition: 'snv', team: 'townsfolk', ability: 'Each night, you learn how many players\' abilities worked abnormally (possibly due to another ability) since dawn today.', firstNightOrder: 51, otherNightOrder: 70, setup: false, reminders: ['Abnormal'], flavorQuote: '"The numbers never lie."', extendedSummary: 'Each night, you learn how many abilities malfunctioned since dawn (due to drunk, poison, etc). High numbers mean interference is happening.', tipsAndTricks: ['Zero means no interference today', 'High numbers suggest Poisoner or drunk', 'Track patterns to find source of interference'], bluffingAs: ['Claim low numbers to seem like no evil interference', 'Numbers are hard to verify'] },
  { id: 'flowergirl', name: 'Flowergirl', edition: 'snv', team: 'townsfolk', ability: 'Each night*, you learn if a Demon voted today.', firstNightOrder: null, otherNightOrder: 58, setup: false, reminders: ['Demon Voted', 'Demon Not Voted'], flavorQuote: '"Flowers for the dead?"', extendedSummary: 'Each night except the first, you learn whether the Demon raised their hand to vote on any execution today (Yes or No).', tipsAndTricks: ['Yes means Demon voted at least once', 'Cross-reference with voting records', 'No means Demon abstained all day'], bluffingAs: ['Claim Yes or No based on voting observed', 'Can frame or clear players'] },
  { id: 'townCrier', name: 'Town Crier', edition: 'snv', team: 'townsfolk', ability: 'Each night*, you learn if a Minion nominated today.', firstNightOrder: null, otherNightOrder: 59, setup: false, reminders: ['Minion Nominated', 'Minion Not Nominated'], flavorQuote: '"Hear ye! Hear ye!"', extendedSummary: 'Each night except the first, you learn whether any Minion made a nomination today (Yes or No).', tipsAndTricks: ['Yes means at least one Minion nominated', 'Track who nominated and cross-reference', 'Minions might avoid nominating'], bluffingAs: ['Claim based on nomination patterns', 'Yes is safer claim'] },
  { id: 'oracle', name: 'Oracle', edition: 'snv', team: 'townsfolk', ability: 'Each night*, you learn how many dead players are evil.', firstNightOrder: null, otherNightOrder: 60, setup: false, reminders: [], flavorQuote: '"The spirits whisper truths."', extendedSummary: 'Each night except the first, you learn how many dead players are evil. Helps identify if executed players were evil.', tipsAndTricks: ['Track count as players die', 'Increasing count means evil dying', 'Stable count means good dying'], bluffingAs: ['Claim counts that match expectations', 'Hard to fake as game progresses'] },
  { id: 'savant', name: 'Savant', edition: 'snv', team: 'townsfolk', ability: 'Each day, you may visit the Storyteller to learn 2 things in private: 1 is true & 1 is false.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"I understand now."', extendedSummary: 'Once per day, you may privately visit the Storyteller. They tell you two statements - one true, one false. You must determine which is which.', tipsAndTricks: ['Privately get customized information', 'Compare statements to deduce truth', 'Powerful but uncertain info source'], bluffingAs: ['Make up plausible statement pairs', 'Private nature makes it easy to lie'] },
  { id: 'seamstress', name: 'Seamstress', edition: 'snv', team: 'townsfolk', ability: 'Once per game, at night, choose 2 players (not yourself): you learn if they are the same alignment.', firstNightOrder: 42, otherNightOrder: 61, setup: false, reminders: ['No Ability'], flavorQuote: '"I can see through the seams."', extendedSummary: 'Once per game, choose two players at night. You learn if they are the same alignment (both good or both evil) or different.', tipsAndTricks: ['Use on suspicious players', 'Different means one good, one evil', 'Same means both good or both evil'], bluffingAs: ['Claim alignment matches you "found"', 'One-shot ability is easy to fake'] },
  { id: 'philosopher', name: 'Philosopher', edition: 'snv', team: 'townsfolk', ability: 'Once per game, at night, choose a good character: gain that ability. If this character is in play, they are drunk.', firstNightOrder: 1, otherNightOrder: 1, setup: false, reminders: ['Is the Philosopher', 'Drunk'], flavorQuote: '"I think, therefore I am."', extendedSummary: 'Once per game, choose a good character to gain their ability. If that exact character is in play, they become drunk while you have the ability.', tipsAndTricks: ['Gain any good ability you want', 'Drunks the real character if in play', 'Very flexible power'], bluffingAs: ['Claim to have become specific role', 'Explains having two abilities'] },
  { id: 'artist', name: 'Artist', edition: 'snv', team: 'townsfolk', ability: 'Once per game, during the day, privately ask the Storyteller any yes/no question.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: ['No Ability'], flavorQuote: '"Let me paint you a picture."', extendedSummary: 'Once per game, during the day, privately ask the Storyteller any yes/no question. They will answer truthfully.', tipsAndTricks: ['Ask carefully worded questions', 'One question must count', 'Consider what info helps most'], bluffingAs: ['Claim you asked specific question', 'Private interaction easy to lie about'] },
  { id: 'juggler', name: 'Juggler', edition: 'snv', team: 'townsfolk', ability: 'On your 1st day, publicly guess up to 5 players\' characters. That night, you learn how many you got correct.', firstNightOrder: null, otherNightOrder: 62, setup: false, reminders: ['Correct'], flavorQuote: '"Watch carefully!"', extendedSummary: 'On day 1, publicly guess up to 5 player-character combinations. That night, you learn how many guesses were correct (0-5).', tipsAndTricks: ['Day 1 only - guess carefully', 'More guesses means more info', 'Public guesses give town info'], bluffingAs: ['Claim number of correct guesses', 'Day 1 timing is fixed'] },
  { id: 'sage', name: 'Sage', edition: 'snv', team: 'townsfolk', ability: 'If the Demon kills you, you learn that it is 1 of 2 players.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Knowledge comes with death."', extendedSummary: 'If you die at night due to Demon attack, you learn 2 players - one of them is the Demon. Information comes with your death.', tipsAndTricks: ['Death gives you Demon info', 'Share info when you die', 'Demon may avoid killing you'], bluffingAs: ['Claim Sage when dead with Demon guess', 'Need to die to "activate"'] },

  // OUTSIDERS
  { id: 'mutant', name: 'Mutant', edition: 'snv', team: 'outsider', ability: 'If you are "mad" about being an Outsider, you might be executed.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"I am... different."', extendedSummary: 'If you act like or claim to be an Outsider (are "mad" about it), the Storyteller might execute you. You must pretend to be Townsfolk or not claim at all.', tipsAndTricks: ['Cannot claim Outsider safely', 'Must play as if you are Townsfolk', 'Execution threat is real'], bluffingAs: ['Hard role to directly claim', 'Mutant hides, not announces'] },
  { id: 'sweetheart', name: 'Sweetheart', edition: 'snv', team: 'outsider', ability: 'When you die, 1 player is drunk from now on.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: ['Drunk'], flavorQuote: '"My heart was too pure."', extendedSummary: 'When you die (by any means), the Storyteller chooses one player to become drunk for the rest of the game.', tipsAndTricks: ['Your death drunks someone permanently', 'Could drunk good or evil player', 'Death has consequences'], bluffingAs: ['Claim after death to explain drunk', 'Outsider with death trigger'] },
  { id: 'barber', name: 'Barber', edition: 'snv', team: 'outsider', ability: 'If you died today or tonight, the Demon may choose 2 players (not another Demon) to swap characters.', firstNightOrder: null, otherNightOrder: 40, setup: false, reminders: ['Haircuts Tonight'], flavorQuote: '"A little off the top?"', extendedSummary: 'If you die (day or night), the Demon may choose 2 players that night to swap characters. Cannot swap another Demon.', tipsAndTricks: ['Your death enables character swaps', 'Demon can create chaos', 'Swaps happen night of your death'], bluffingAs: ['Explain character confusion', 'Claim when characters seem swapped'] },
  { id: 'klutz', name: 'Klutz', edition: 'snv', team: 'outsider', ability: 'When you learn that you died, publicly choose 1 alive player: if they are evil, your team loses.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Oops!"', extendedSummary: 'When you die and learn it, you must publicly choose an alive player. If they are evil, good loses immediately. Choose carefully.', tipsAndTricks: ['Dying triggers lose condition risk', 'Must choose good player to not lose', 'Be very careful who you pick'], bluffingAs: ['Dangerous ability to have', 'Claim explains pressure on choice'] },

  // MINIONS
  { id: 'evilTwin', name: 'Evil Twin', edition: 'snv', team: 'minion', ability: 'You & an opposing player know each other. If the good player is executed, evil wins. Good can\'t win if you both live.', firstNightOrder: 23, otherNightOrder: null, setup: true, reminders: ['Twin'], flavorQuote: '"We are one."', extendedSummary: 'You and a good player are Twins and know each other. If the good Twin is executed, evil wins. Good cannot win while both Twins live.', tipsAndTricks: ['Your Twin is your shield', 'Executing good Twin wins for evil', 'Both must die for good to win normally'], fightingThe: ['Identify which Twin is evil', 'Both Twins must eventually die', 'Never execute blindly between Twins'] },
  { id: 'witch', name: 'Witch', edition: 'snv', team: 'minion', ability: 'Each night, choose a player: if they nominate tomorrow, they die. If just 3 players live, you lose this ability.', firstNightOrder: 24, otherNightOrder: 14, setup: false, reminders: ['Cursed'], flavorQuote: '"I\'ll get you, my pretty!"', extendedSummary: 'Each night, curse a player. If they nominate anyone tomorrow, they die immediately. At 3 players, you lose this ability.', tipsAndTricks: ['Silence good players through fear', 'Kills happen on nomination', 'Lose ability at 3 players'], fightingThe: ['Death on nomination means Witch', 'Track who nominated before deaths', 'Safe at 3 players remaining'] },
  { id: 'cerenovus', name: 'Cerenovus', edition: 'snv', team: 'minion', ability: 'Each night, choose a player & a good character: they are "mad" they are this character tomorrow, or might be executed.', firstNightOrder: 25, otherNightOrder: 15, setup: false, reminders: ['Mad'], flavorQuote: '"Believe what I tell you to believe."', extendedSummary: 'Each night, choose a player and a good character. Tomorrow, they must pretend to be that character or risk execution by Storyteller.', tipsAndTricks: ['Force players to lie', 'Creates conflicting claims', 'Madness causes chaos'], fightingThe: ['Conflicting claims might be madness', 'Ask why someone changed their story', 'Cerenovus forces false claims'] },
  { id: 'pitHag', name: 'Pit-Hag', edition: 'snv', team: 'minion', ability: 'Each night*, choose a player & a character they become (if not-in-play). If a Demon is made, deaths tonight are arbitrary.', firstNightOrder: null, otherNightOrder: 16, setup: false, reminders: [], flavorQuote: '"Let me fix that for you."', extendedSummary: 'Each night except first, change a player into a new character (not already in play). If you create a new Demon, all deaths that night are Storyteller\'s choice.', tipsAndTricks: ['Change characters at will', 'Can create new Demon', 'Disrupts ability expectations'], fightingThe: ['Characters might change overnight', 'Role claims may become outdated', 'Pit-Hag creates chaos'] },

  // DEMONS
  { id: 'fangGu', name: 'Fang Gu', edition: 'snv', team: 'demon', ability: 'Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu & you die instead. [+1 Outsider]', firstNightOrder: null, otherNightOrder: 29, setup: true, reminders: ['Dead', 'Once'], flavorQuote: '"My venom is eternal."', extendedSummary: 'Kill each night. First time you kill an Outsider, they become the new evil Fang Gu and you die instead. Setup adds 1 Outsider.', tipsAndTricks: ['Avoid Outsiders or use them strategically', 'Can pass to Outsider if dying', 'Extra Outsider in setup'], fightingThe: ['Fang Gu can jump to Outsider', 'Newly evil Outsider is new Demon', 'Watch Outsiders carefully'] },
  { id: 'vigormortis', name: 'Vigormortis', edition: 'snv', team: 'demon', ability: 'Each night*, choose a player: they die. Minions you kill keep their ability & poison 1 Townsfolk neighbour. [-1 Outsider]', firstNightOrder: null, otherNightOrder: 30, setup: true, reminders: ['Dead', 'Has Ability', 'Poisoned'], flavorQuote: '"Death is just the beginning."', extendedSummary: 'Kill each night. Minions you kill keep their ability and poison one Townsfolk neighbor. Setup removes 1 Outsider.', tipsAndTricks: ['Kill your own Minions for benefits', 'Dead Minions still have powers', 'Fewer Outsiders in game'], fightingThe: ['Dead Minions might still function', 'Unexplained poison suggests Vigormortis', 'Minion deaths empower this Demon'] },
  { id: 'noDashii', name: 'No Dashii', edition: 'snv', team: 'demon', ability: 'Each night*, choose a player: they die. Your 2 Townsfolk neighbours are poisoned.', firstNightOrder: null, otherNightOrder: 31, setup: false, reminders: ['Dead', 'Poisoned'], flavorQuote: '"The corruption spreads."', extendedSummary: 'Kill each night. Your two nearest Townsfolk neighbors (alive or dead) are poisoned permanently while you live.', tipsAndTricks: ['Poison spreads from your position', 'Neighbors get false info', 'Position matters greatly'], fightingThe: ['Two Townsfolk near No Dashii are poisoned', 'Look for clustered bad info', 'Find the poison center'] },
  { id: 'vortox', name: 'Vortox', edition: 'snv', team: 'demon', ability: 'Each night*, choose a player: they die. Townsfolk abilities yield false info. Each day, if no-one is executed, evil wins.', firstNightOrder: null, otherNightOrder: 32, setup: false, reminders: ['Dead'], flavorQuote: '"Nothing is true."', extendedSummary: 'Kill each night. All Townsfolk abilities give false information. If any day passes without an execution, evil wins immediately.', tipsAndTricks: ['All Townsfolk info is false', 'Must execute every day', 'Use false info in reverse'], fightingThe: ['Vortox = all Townsfolk info inverted', 'Must execute daily or evil wins', 'Info being consistently wrong suggests Vortox'] },
];

// ===================
// TRAVELLERS
// ===================

export const TRAVELLERS: Character[] = [
  // Trouble Brewing Travellers
  { id: 'scapegoat', name: 'Scapegoat', edition: 'traveler', team: 'traveler', ability: 'If a player of your alignment is executed, you might be executed instead.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"It was all my fault."', extendedSummary: 'If a player of your alignment is executed, the Storyteller may execute you instead. You take their place on the chopping block.', tipsAndTricks: ['You can save your team from execution', 'Alignment determines who you save', 'Storyteller chooses when to activate'], bluffingAs: ['Traveller - enters game later'] },
  { id: 'gunslinger', name: 'Gunslinger', edition: 'traveler', team: 'traveler', ability: 'Each day, after the 1st vote has been tallied, you may choose a player that voted: they die.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"This town ain\'t big enough for the two of us."', extendedSummary: 'Each day, after the first vote is counted, you may kill any player who voted in that vote. Very aggressive ability.', tipsAndTricks: ['Kill players who vote suspiciously', 'Powerful but dangerous', 'Use to eliminate evil voters'], bluffingAs: ['Traveller ability'] },
  { id: 'beggar', name: 'Beggar', edition: 'traveler', team: 'traveler', ability: 'You must use a vote token to vote. If a dead player gives you theirs, you learn their alignment. You are sober & healthy.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Spare some change?"', extendedSummary: 'You need vote tokens to vote. Dead players giving you their token reveals their alignment. You cannot be drunk or poisoned.', tipsAndTricks: ['Collect vote tokens from dead', 'Learn alignments through tokens', 'Always sober and healthy'], bluffingAs: ['Traveller role'] },
  { id: 'bureaucrat', name: 'Bureaucrat', edition: 'traveler', team: 'traveler', ability: 'Each night, choose a player (not yourself): their vote counts as 3 votes tomorrow.', firstNightOrder: 2, otherNightOrder: 2, setup: false, reminders: ['3 Votes'], flavorQuote: '"Please fill out form 27B stroke 6."', extendedSummary: 'Each night, choose a player. Their vote counts as 3 votes tomorrow, making them very influential in executions.', tipsAndTricks: ['Empower trusted players', 'Triple votes swing executions', 'Can help good or evil'], bluffingAs: ['Traveller'] },
  { id: 'thief', name: 'Thief', edition: 'traveler', team: 'traveler', ability: 'Each night, choose a player (not yourself): their vote counts negatively tomorrow.', firstNightOrder: 3, otherNightOrder: 3, setup: false, reminders: ['Negative Vote'], flavorQuote: '"What\'s yours is mine."', extendedSummary: 'Each night, choose a player. Their vote counts as -1 tomorrow, subtracting from vote totals instead of adding.', tipsAndTricks: ['Negate evil votes', 'Powerful vote manipulation', 'Negative votes reduce totals'], bluffingAs: ['Traveller ability'] },
  
  // Bad Moon Rising Travellers
  { id: 'apprentice', name: 'Apprentice', edition: 'traveler', team: 'traveler', ability: 'On your 1st night, you gain a Townsfolk ability (if good) or a Minion ability (if evil).', firstNightOrder: 4, otherNightOrder: null, setup: false, reminders: ['Is the Apprentice'], flavorQuote: '"Teach me, master."', extendedSummary: 'On your first night, you gain a Townsfolk ability (if good) or Minion ability (if evil). You have this ability for the rest of the game.', tipsAndTricks: ['Gain powerful ability permanently', 'Alignment determines ability type', 'Flexible role'], bluffingAs: ['Traveller with gained ability'] },
  { id: 'matron', name: 'Matron', edition: 'traveler', team: 'traveler', ability: 'Each day, you may choose up to 3 sets of 2 players to swap seats. Players may not leave their seats to talk in private.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Children, settle down!"', extendedSummary: 'Each day, swap up to 3 pairs of player seats. Players cannot leave seats for private conversations.', tipsAndTricks: ['Control seating arrangements', 'Prevent private talks', 'Affects neighbor-based abilities'], bluffingAs: ['Traveller role'] },
  { id: 'judge', name: 'Judge', edition: 'traveler', team: 'traveler', ability: 'Once per game, if another player nominated, you may choose to force the current execution to pass or fail.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: ['No Ability'], flavorQuote: '"Order in the court!"', extendedSummary: 'Once per game, after another player nominates, you can force that execution to either succeed or fail, regardless of votes.', tipsAndTricks: ['Override any execution vote', 'Save or condemn at will', 'One-time powerful ability'], bluffingAs: ['Traveller'] },
  { id: 'bishop', name: 'Bishop', edition: 'traveler', team: 'traveler', ability: 'Only the Storyteller can nominate. At least 1 opposing player is executed each day.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"The will of God shall be done."', extendedSummary: 'Only Storyteller nominates while you live. At least one player of opposing alignment to you must be executed each day.', tipsAndTricks: ['Removes player nominations', 'Forced opposing executions', 'Very game-changing'], bluffingAs: ['Traveller role'] },
  { id: 'voudon', name: 'Voudon', edition: 'traveler', team: 'traveler', ability: 'Only dead players may vote. They do not need a vote token to do so. Dead players can vote up to 3 times.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"The dead speak through me."', extendedSummary: 'Only dead players vote (no tokens needed). Each dead player can vote up to 3 times during the game.', tipsAndTricks: ['Dead control votes', 'Living cannot vote', 'Changes game dynamics entirely'], bluffingAs: ['Traveller'] },

  // Sects & Violets Travellers
  { id: 'barista', name: 'Barista', edition: 'traveler', team: 'traveler', ability: 'Each night, until dusk, 1) a player becomes sober, healthy & gets true info, or 2) their ability works twice. The Storyteller chooses.', firstNightOrder: 5, otherNightOrder: 5, setup: false, reminders: ['Sober & Healthy', 'Acts Twice'], flavorQuote: '"Double shot?"', extendedSummary: 'Each night, Storyteller picks either: make one player sober and healthy with true info, OR make their ability work twice.', tipsAndTricks: ['Enhance player abilities', 'Cure drunk/poison or double power', 'Storyteller chooses effect'], bluffingAs: ['Traveller role'] },
  { id: 'harlot', name: 'Harlot', edition: 'traveler', team: 'traveler', ability: 'Each night*, choose a living player: if they agree, you learn their character, but you both might die.', firstNightOrder: null, otherNightOrder: 6, setup: false, reminders: ['Dead'], flavorQuote: '"Come with me, darling."', extendedSummary: 'Each night, choose a player. If they agree to your visit, you learn their character but either or both of you might die.', tipsAndTricks: ['Risky character learning', 'Both can die from visit', 'Player must agree'], bluffingAs: ['Traveller'] },
  { id: 'butcher', name: 'Butcher', edition: 'traveler', team: 'traveler', ability: 'Each day, after the 1st execution, you may nominate again.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Who\'s next?"', extendedSummary: 'After the first execution each day, you may make one additional nomination. Enables double executions.', tipsAndTricks: ['Two executions possible', 'Speeds up game', 'Use wisely'], bluffingAs: ['Traveller ability'] },
  { id: 'bonecollector', name: 'Bone Collector', edition: 'traveler', team: 'traveler', ability: 'Once per game, at night*, choose a dead player: they regain their ability until dusk.', firstNightOrder: null, otherNightOrder: 42, setup: false, reminders: ['No Ability', 'Has Ability'], flavorQuote: '"I collect memories."', extendedSummary: 'Once per game, revive a dead player ability until dusk. They can use their ability one more time.', tipsAndTricks: ['Resurrect powerful abilities', 'One-time use', 'Choose wisely'], bluffingAs: ['Traveller'] },
  { id: 'deviant', name: 'Deviant', edition: 'traveler', team: 'traveler', ability: 'If you were funny today, you can\'t die by exile.', firstNightOrder: null, otherNightOrder: null, setup: false, reminders: [], flavorQuote: '"Ha ha ha!"', extendedSummary: 'If you made people laugh today (Storyteller judges), you cannot be exiled. Humor protects you.', tipsAndTricks: ['Be entertaining to survive', 'Exile protection through comedy', 'Storyteller judges humor'], bluffingAs: ['Traveller role'] },
];

// ===================
// JINXES
// ===================

export const JINXES: Jinx[] = [
  // Spy jinxes
  { character1: 'spy', character2: 'magician', reason: 'When the Spy sees the Grimoire, the Demon and Magician\'s character tokens are swapped.' },
  { character1: 'spy', character2: 'poppy_grower', reason: 'If the Poppy Grower is in play, the Spy does not see the Grimoire until the Poppy Grower dies.' },
  { character1: 'spy', character2: 'damsel', reason: 'Only 1 jinxed character can be in play.' },
  { character1: 'spy', character2: 'heretic', reason: 'Only 1 jinxed character can be in play.' },
  
  // Widow jinxes
  { character1: 'widow', character2: 'magician', reason: 'When the Widow sees the Grimoire, the Demon and Magician\'s character tokens are swapped.' },
  { character1: 'widow', character2: 'poppy_grower', reason: 'If the Poppy Grower is in play, the Widow does not see the Grimoire until the Poppy Grower dies.' },
  { character1: 'widow', character2: 'damsel', reason: 'Only 1 jinxed character can be in play.' },
  { character1: 'widow', character2: 'heretic', reason: 'Only 1 jinxed character can be in play.' },
  
  // Recluse jinxes
  { character1: 'recluse', character2: 'spy', reason: 'Only 1 jinxed character can be in play.' },
  
  // Lunatic jinxes
  { character1: 'lunatic', character2: 'mathematician', reason: 'The Mathematician learns if the Lunatic\'s ability worked correctly, but not if the Demon\'s did.' },
  
  // Godfather jinxes
  { character1: 'godfather', character2: 'heretic', reason: 'Only 1 jinxed character can be in play.' },
  
  // Pit-Hag jinxes
  { character1: 'pitHag', character2: 'heretic', reason: 'A Heretic cannot be created.' },
  { character1: 'pitHag', character2: 'damsel', reason: 'If the Pit-Hag creates a Damsel, the Storyteller chooses which player it is.' },
  
  // Fang Gu jinxes
  { character1: 'fangGu', character2: 'scarletwoman', reason: 'If the Fang Gu chooses an Outsider and dies, the Scarlet Woman does not become the Fang Gu.' },
  
  // Vigormortis jinxes
  { character1: 'vigormortis', character2: 'scarletwoman', reason: 'If the Vigormortis kills the Scarlet Woman, she does not become poisoned.' },
  
  // Evil Twin jinxes
  { character1: 'evilTwin', character2: 'magician', reason: 'The Demon learns a Good Twin rather than a Minion.' },
];

// ===================
// OFFICIAL SCRIPTS
// ===================

export const OFFICIAL_SCRIPTS = [
  {
    id: 'tb',
    name: 'Trouble Brewing',
    author: 'The Pandemonium Institute',
    description: 'The classic introductory script. Balanced and beginner-friendly with clear-cut roles and straightforward abilities.',
    isOfficial: true,
    characters: TROUBLE_BREWING.map(c => c.id),
  },
  {
    id: 'bmr',
    name: 'Bad Moon Rising',
    author: 'The Pandemonium Institute', 
    description: 'A deadly script where death comes often. Features resurrection, protection, and a focus on the night phase.',
    isOfficial: true,
    characters: BAD_MOON_RISING.map(c => c.id),
  },
  {
    id: 'snv',
    name: 'Sects & Violets',
    author: 'The Pandemonium Institute',
    description: 'A mad script focused on information, madness, and manipulation. Features character-swapping and mental pressure.',
    isOfficial: true,
    characters: SECTS_AND_VIOLETS.map(c => c.id),
  },
];

// ===================
// COMBINED DATA
// ===================

export const ALL_CHARACTERS: Character[] = [
  ...TROUBLE_BREWING,
  ...BAD_MOON_RISING,
  ...SECTS_AND_VIOLETS,
  ...TRAVELLERS,
];

// Helper function to get character by ID
export function getCharacterById(id: string): Character | undefined {
  return ALL_CHARACTERS.find(c => c.id === id);
}

// Helper function to get all jinxes for a character
export function getJinxesForCharacter(characterId: string): Jinx[] {
  return JINXES.filter(j => j.character1 === characterId || j.character2 === characterId);
}

// Helper function to check for jinxes between two characters
export function getJinxBetween(char1Id: string, char2Id: string): Jinx | undefined {
  return JINXES.find(j => 
    (j.character1 === char1Id && j.character2 === char2Id) ||
    (j.character1 === char2Id && j.character2 === char1Id)
  );
}

// Helper function to get characters by edition
export function getCharactersByEdition(edition: string): Character[] {
  return ALL_CHARACTERS.filter(c => c.edition === edition);
}

// Helper function to get characters by team
export function getCharactersByTeam(team: string): Character[] {
  return ALL_CHARACTERS.filter(c => c.team === team);
}
