// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/reference-redesign/Candlelit.tsx": () => import("../components/mockups/reference-redesign/Candlelit.tsx"),
  "./components/mockups/reference-redesign/Codex.tsx": () => import("../components/mockups/reference-redesign/Codex.tsx")
};
