/**
 * Download official BotC token art into client/public/characters/ (self-hosted per the
 * TPI Community Created Content Policy). Run once: npm run fetch-icons. Idempotent —
 * skips files already present.
 */
import { mkdirSync, existsSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';

const ICONS: { url: string; path: string }[] = [
  { url: "https://release.botc.app/resources/characters/tb/washerwoman_g.webp", path: "/characters/tb/washerwoman_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/librarian_g.webp", path: "/characters/tb/librarian_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/investigator_g.webp", path: "/characters/tb/investigator_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/chef_g.webp", path: "/characters/tb/chef_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/empath_g.webp", path: "/characters/tb/empath_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/fortuneteller_g.webp", path: "/characters/tb/fortuneteller_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/undertaker_g.webp", path: "/characters/tb/undertaker_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/monk_g.webp", path: "/characters/tb/monk_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/ravenkeeper_g.webp", path: "/characters/tb/ravenkeeper_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/virgin_g.webp", path: "/characters/tb/virgin_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/slayer_g.webp", path: "/characters/tb/slayer_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/soldier_g.webp", path: "/characters/tb/soldier_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/mayor_g.webp", path: "/characters/tb/mayor_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/butler_g.webp", path: "/characters/tb/butler_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/drunk_g.webp", path: "/characters/tb/drunk_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/recluse_g.webp", path: "/characters/tb/recluse_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/saint_g.webp", path: "/characters/tb/saint_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/poisoner_e.webp", path: "/characters/tb/poisoner_e.webp" },
  { url: "https://release.botc.app/resources/characters/tb/spy_e.webp", path: "/characters/tb/spy_e.webp" },
  { url: "https://release.botc.app/resources/characters/tb/scarletwoman_e.webp", path: "/characters/tb/scarletwoman_e.webp" },
  { url: "https://release.botc.app/resources/characters/tb/baron_e.webp", path: "/characters/tb/baron_e.webp" },
  { url: "https://release.botc.app/resources/characters/tb/imp_e.webp", path: "/characters/tb/imp_e.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/grandmother_g.webp", path: "/characters/bmr/grandmother_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/sailor_g.webp", path: "/characters/bmr/sailor_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/chambermaid_g.webp", path: "/characters/bmr/chambermaid_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/exorcist_g.webp", path: "/characters/bmr/exorcist_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/innkeeper_g.webp", path: "/characters/bmr/innkeeper_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/gambler_g.webp", path: "/characters/bmr/gambler_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/gossip_g.webp", path: "/characters/bmr/gossip_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/courtier_g.webp", path: "/characters/bmr/courtier_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/professor_g.webp", path: "/characters/bmr/professor_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/minstrel_g.webp", path: "/characters/bmr/minstrel_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/tealady_g.webp", path: "/characters/bmr/tealady_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/pacifist_g.webp", path: "/characters/bmr/pacifist_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/fool_g.webp", path: "/characters/bmr/fool_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/tinker_g.webp", path: "/characters/bmr/tinker_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/moonchild_g.webp", path: "/characters/bmr/moonchild_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/goon_g.webp", path: "/characters/bmr/goon_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/lunatic_g.webp", path: "/characters/bmr/lunatic_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/godfather_e.webp", path: "/characters/bmr/godfather_e.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/devilsadvocate_e.webp", path: "/characters/bmr/devilsadvocate_e.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/assassin_e.webp", path: "/characters/bmr/assassin_e.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/mastermind_e.webp", path: "/characters/bmr/mastermind_e.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/zombuul_e.webp", path: "/characters/bmr/zombuul_e.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/pukka_e.webp", path: "/characters/bmr/pukka_e.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/shabaloth_e.webp", path: "/characters/bmr/shabaloth_e.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/po_e.webp", path: "/characters/bmr/po_e.webp" },
  { url: "https://release.botc.app/resources/characters/snv/clockmaker_g.webp", path: "/characters/snv/clockmaker_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/dreamer_g.webp", path: "/characters/snv/dreamer_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/snakecharmer_g.webp", path: "/characters/snv/snakecharmer_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/mathematician_g.webp", path: "/characters/snv/mathematician_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/flowergirl_g.webp", path: "/characters/snv/flowergirl_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/towncrier_g.webp", path: "/characters/snv/towncrier_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/oracle_g.webp", path: "/characters/snv/oracle_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/savant_g.webp", path: "/characters/snv/savant_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/seamstress_g.webp", path: "/characters/snv/seamstress_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/philosopher_g.webp", path: "/characters/snv/philosopher_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/artist_g.webp", path: "/characters/snv/artist_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/juggler_g.webp", path: "/characters/snv/juggler_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/sage_g.webp", path: "/characters/snv/sage_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/mutant_g.webp", path: "/characters/snv/mutant_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/sweetheart_g.webp", path: "/characters/snv/sweetheart_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/barber_g.webp", path: "/characters/snv/barber_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/klutz_g.webp", path: "/characters/snv/klutz_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/eviltwin_e.webp", path: "/characters/snv/eviltwin_e.webp" },
  { url: "https://release.botc.app/resources/characters/snv/witch_e.webp", path: "/characters/snv/witch_e.webp" },
  { url: "https://release.botc.app/resources/characters/snv/cerenovus_e.webp", path: "/characters/snv/cerenovus_e.webp" },
  { url: "https://release.botc.app/resources/characters/snv/pithag_e.webp", path: "/characters/snv/pithag_e.webp" },
  { url: "https://release.botc.app/resources/characters/snv/fanggu_e.webp", path: "/characters/snv/fanggu_e.webp" },
  { url: "https://release.botc.app/resources/characters/snv/vigormortis_e.webp", path: "/characters/snv/vigormortis_e.webp" },
  { url: "https://release.botc.app/resources/characters/snv/nodashii_e.webp", path: "/characters/snv/nodashii_e.webp" },
  { url: "https://release.botc.app/resources/characters/snv/vortox_e.webp", path: "/characters/snv/vortox_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/acrobat_g.webp", path: "/characters/carousel/acrobat_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/alchemist_g.webp", path: "/characters/carousel/alchemist_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/alsaahir_g.webp", path: "/characters/carousel/alsaahir_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/amnesiac_g.webp", path: "/characters/carousel/amnesiac_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/atheist_g.webp", path: "/characters/carousel/atheist_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/balloonist_g.webp", path: "/characters/carousel/balloonist_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/banshee_g.webp", path: "/characters/carousel/banshee_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/bountyhunter_g.webp", path: "/characters/carousel/bountyhunter_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/cannibal_g.webp", path: "/characters/carousel/cannibal_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/choirboy_g.webp", path: "/characters/carousel/choirboy_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/cultleader_g.webp", path: "/characters/carousel/cultleader_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/engineer_g.webp", path: "/characters/carousel/engineer_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/farmer_g.webp", path: "/characters/carousel/farmer_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/fisherman_g.webp", path: "/characters/carousel/fisherman_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/general_g.webp", path: "/characters/carousel/general_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/highpriestess_g.webp", path: "/characters/carousel/highpriestess_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/huntsman_g.webp", path: "/characters/carousel/huntsman_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/king_g.webp", path: "/characters/carousel/king_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/knight_g.webp", path: "/characters/carousel/knight_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/lycanthrope_g.webp", path: "/characters/carousel/lycanthrope_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/magician_g.webp", path: "/characters/carousel/magician_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/nightwatchman_g.webp", path: "/characters/carousel/nightwatchman_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/noble_g.webp", path: "/characters/carousel/noble_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/pixie_g.webp", path: "/characters/carousel/pixie_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/poppygrower_g.webp", path: "/characters/carousel/poppygrower_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/preacher_g.webp", path: "/characters/carousel/preacher_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/princess_g.webp", path: "/characters/carousel/princess_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/shugenja_g.webp", path: "/characters/carousel/shugenja_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/steward_g.webp", path: "/characters/carousel/steward_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/villageidiot_g.webp", path: "/characters/carousel/villageidiot_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/damsel_g.webp", path: "/characters/carousel/damsel_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/golem_g.webp", path: "/characters/carousel/golem_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/hatter_g.webp", path: "/characters/carousel/hatter_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/heretic_g.webp", path: "/characters/carousel/heretic_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/hermit_g.webp", path: "/characters/carousel/hermit_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/ogre_g.webp", path: "/characters/carousel/ogre_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/plaguedoctor_g.webp", path: "/characters/carousel/plaguedoctor_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/politician_g.webp", path: "/characters/carousel/politician_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/puzzlemaster_g.webp", path: "/characters/carousel/puzzlemaster_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/snitch_g.webp", path: "/characters/carousel/snitch_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/zealot_g.webp", path: "/characters/carousel/zealot_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/boffin_e.webp", path: "/characters/carousel/boffin_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/boomdandy_e.webp", path: "/characters/carousel/boomdandy_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/fearmonger_e.webp", path: "/characters/carousel/fearmonger_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/goblin_e.webp", path: "/characters/carousel/goblin_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/harpy_e.webp", path: "/characters/carousel/harpy_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/marionette_e.webp", path: "/characters/carousel/marionette_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/mezepheles_e.webp", path: "/characters/carousel/mezepheles_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/organgrinder_e.webp", path: "/characters/carousel/organgrinder_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/psychopath_e.webp", path: "/characters/carousel/psychopath_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/summoner_e.webp", path: "/characters/carousel/summoner_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/vizier_e.webp", path: "/characters/carousel/vizier_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/widow_e.webp", path: "/characters/carousel/widow_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/wizard_e.webp", path: "/characters/carousel/wizard_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/wraith_e.webp", path: "/characters/carousel/wraith_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/xaan_e.webp", path: "/characters/carousel/xaan_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/alhadikhia_e.webp", path: "/characters/carousel/alhadikhia_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/kazali_e.webp", path: "/characters/carousel/kazali_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/legion_e.webp", path: "/characters/carousel/legion_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/leviathan_e.webp", path: "/characters/carousel/leviathan_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/lilmonsta_e.webp", path: "/characters/carousel/lilmonsta_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/lleech_e.webp", path: "/characters/carousel/lleech_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/lordoftyphon_e.webp", path: "/characters/carousel/lordoftyphon_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/ojo_e.webp", path: "/characters/carousel/ojo_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/riot_e.webp", path: "/characters/carousel/riot_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/yaggababble_e.webp", path: "/characters/carousel/yaggababble_e.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/cacklejack_g.webp", path: "/characters/carousel/cacklejack_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/gangster_g.webp", path: "/characters/carousel/gangster_g.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/gnome_g.webp", path: "/characters/carousel/gnome_g.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/angel.webp", path: "/characters/fabled/angel.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/buddhist.webp", path: "/characters/fabled/buddhist.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/doomsayer.webp", path: "/characters/fabled/doomsayer.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/fiddler.webp", path: "/characters/fabled/fiddler.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/revolutionary.webp", path: "/characters/fabled/revolutionary.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/toymaker.webp", path: "/characters/fabled/toymaker.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/djinn.webp", path: "/characters/fabled/djinn.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/duchess.webp", path: "/characters/fabled/duchess.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/fibbin.webp", path: "/characters/fabled/fibbin.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/sentinel.webp", path: "/characters/fabled/sentinel.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/deusexfiasco.webp", path: "/characters/carousel/deusexfiasco.webp" },
  { url: "https://release.botc.app/resources/characters/carousel/ferryman.webp", path: "/characters/carousel/ferryman.webp" },
  { url: "https://release.botc.app/resources/characters/loric/stormcatcher.webp", path: "/characters/loric/stormcatcher.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/hellslibrarian.webp", path: "/characters/fabled/hellslibrarian.webp" },
  { url: "https://release.botc.app/resources/characters/fabled/spiritofivory.webp", path: "/characters/fabled/spiritofivory.webp" },
  { url: "https://release.botc.app/resources/characters/tb/scapegoat_g.webp", path: "/characters/tb/scapegoat_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/gunslinger_g.webp", path: "/characters/tb/gunslinger_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/beggar_g.webp", path: "/characters/tb/beggar_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/bureaucrat_g.webp", path: "/characters/tb/bureaucrat_g.webp" },
  { url: "https://release.botc.app/resources/characters/tb/thief_g.webp", path: "/characters/tb/thief_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/apprentice_g.webp", path: "/characters/bmr/apprentice_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/matron_g.webp", path: "/characters/bmr/matron_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/judge_g.webp", path: "/characters/bmr/judge_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/bishop_g.webp", path: "/characters/bmr/bishop_g.webp" },
  { url: "https://release.botc.app/resources/characters/bmr/voudon_g.webp", path: "/characters/bmr/voudon_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/barista_g.webp", path: "/characters/snv/barista_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/harlot_g.webp", path: "/characters/snv/harlot_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/butcher_g.webp", path: "/characters/snv/butcher_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/bonecollector_g.webp", path: "/characters/snv/bonecollector_g.webp" },
  { url: "https://release.botc.app/resources/characters/snv/deviant_g.webp", path: "/characters/snv/deviant_g.webp" },
];

const PUBLIC = join(process.cwd(), 'client', 'public');

async function main() {
  let got = 0, skipped = 0; const failed: string[] = [];
  for (const { url, path } of ICONS) {
    const dest = join(PUBLIC, path);
    if (existsSync(dest)) { skipped++; continue; }
    try {
      const r = await fetch(url);
      if (!r.ok) { failed.push(`${url} (${r.status})`); continue; }
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, Buffer.from(await r.arrayBuffer()));
      got++;
    } catch (e) { failed.push(`${url} (${(e as Error).message})`); }
  }
  console.log(`fetched ${got}, skipped ${skipped}, failed ${failed.length}`);
  if (failed.length) { failed.forEach(f => console.error('  FAIL', f)); process.exit(1); }
  console.log('All 171 icons present under client/public/characters/.');
}
main();
